### ISSUE TITLE
Complete linking

### ISSUE THREAD

**Issue by sangjunp4rk** [OliverGengenbach/f1-3-c2p1-colmar-academy#2]
You correctly made the link references but never specified the actual divs. You need to write stuff like `<class div='online'>` so that when you click on something you navigate to the correct spots.

https://github.com/OliverGengenbach/f1-3-c2p1-colmar-academy/blob/master/CapstoneProjectColmarAcademy/index.html#L18-L21

**Comment by OliverGengenbach** [comment]
Ok, included now. However not styled (yet).
