### ISSUE TITLE
Be more consistent with indentation

### ISSUE THREAD

**Issue by sangjunp4rk** [OliverGengenbach/f1-3-c2p1-colmar-academy#4]
Make sure tags that open on a certain indentation level closes on the same indentation level. Right now, your indentation levels are inconsistent. Having consistent levels helps make your code cleaner.

https://github.com/OliverGengenbach/f1-3-c2p1-colmar-academy/blob/master/CapstoneProjectColmarAcademy/index.html#L39-L41

**Comment by OliverGengenbach** [comment]
ok, improved that.
